### Rcode to query Food Habits
## K holsman 2020

#################################
## !!! Must be run in 32 bit R
#################################

   qry_PreyList_lkup <-"SELECT PP.PREY_NODC, NPREY.ECOPATH_Prey,NPREY.NODC,NPREY.RACE,NPREY.NAME, NPREY.GOAPOLL_PREY,NPREY.BSIERP_PREY

		FROM foodlab.nodc NPREY, foodlab.predprey PP
		
		Where  PP.PRED_NODC = NPREY.nodc 
		GROUP BY PP.PREY_NODC, NPREY.ECOPATH_Prey,NPREY.NODC,NPREY.RACE,NPREY.NAME, NPREY.GOAPOLL_PREY,NPREY.BSIERP_PREY;"

	#______________________________________________________


	qry_PredList_lkup<-"SELECT PP.PRED_NODC, NPRED.ECOPATH_Pred,NPRED.NODC,NPRED.RACE,NPRED.NAME

		FROM foodlab.preylen PP, foodlab.nodc NPRED
		
		Where  PP.PRED_NODC = NPRED.nodc 
		GROUP BY PP.PRED_NODC, NPRED.ECOPATH_Pred,NPRED.NODC,NPRED.RACE,NPRED.NAME;"
	#______________________________________________________

	qry_predLen_lkup<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   
		--HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,
		PP.PREDJOIN, PP.PRED_LEN, NPREY.ECOPATH_Prey

		FROM foodlab.preylen PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
		kerim_strata TT
		--, racebase.haul HRB

		--WHERE (HH.GEAR_TEMP is not null) 
		Where (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(NPREY.GOAPOLL_PREY = 'KING CRAB')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		--AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		--or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		--or NPRED.GOAPOLL_pred='PACIFIC COD'
		--or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		--or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		--or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, 
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID, NPREY.ECOPATH_Prey, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, NPREY.ECOPATH_Prey;"
	#______________________________________________________
	qry_Crab_predLen_lkup<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,  
		-- HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,
		PP.PREDJOIN, PP.PRED_LEN, NPREY.ECOPATH_Prey

		FROM foodlab.preylen PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
		kerim_strata TT
		--, racebase.haul HRB

		--WHERE (HH.GEAR_TEMP is not null) 
		WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		AND(NPREY.GOAPOLL_PREY = 'KING CRAB')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		--AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		--or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		--or NPRED.GOAPOLL_pred='PACIFIC COD'
		--or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		--or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		--or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG,
		-- HRB.START_LATITUDE, HRB.START_LONGITUDE,
		HH.STATIONID, NPREY.ECOPATH_Prey, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN;"

	#---------------------------------------------------------------
	qry_Crab_pred_lkup<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,  
		-- HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
		sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

		FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
		kerim_strata TT
		--racebase.haul HRB

		--WHERE (HH.GEAR_TEMP is not null) 
		WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		AND(NPREY.GOAPOLL_PREY = 'KING CRAB')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		--AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		--or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		--or NPRED.GOAPOLL_pred='PACIFIC COD'
		--or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		--or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		--or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG,
		-- HRB.START_LATITUDE, HRB.START_LONGITUDE,
		HH.STATIONID, NPREY.ECOPATH_Prey, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"

	#---------------------------------------------------------------
	
	qry_Station_lkup<-"SELECT HH.HAULJOIN,
		HH.REGION, HH.STRATUM as STRATUM2, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP,
		HH.STATIONID as STATIONID2, HH.RLAT, HH.RLONG,  
		HRB.STRATUM,HRB.STATIONID,
		HRB.START_LATITUDE as RLAT_RACEBASE,
		HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP

		FROM kerim_strata TT, racebase.haul HRB,foodlab.haul HH

		--WHERE (HH.GEAR_TEMP is not null) 
		Where (HRB.VESSEL = HH.VESSEL AND HRB.CRUISE = HH.CRUISE AND HRB.HAUL = HH.HAUL) 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION)
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')


		GROUP BY HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HRB.STRATUM, HRB.STATIONID,
		HH.RLAT,HH.RLONG, HRB.START_LATITUDE, HRB.START_LONGITUDE, HH.STATIONID, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP;"

	#---------------------------------------------------------------
	# Main queries below
	#---------------------------------------------------------------
		

	qry_KH_PredPrey_all<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, 
		NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   
		--HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_NODC, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
		sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

		FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
		kerim_strata TT 
		--,racebase.haul HRB

		--WHERE (HH.GEAR_TEMP is not null) 
		WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(hh.region = 'BS')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		--AND (NPRED.ECOPATH_Pred <>  'NA' )
		--AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		--or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		--or NPRED.GOAPOLL_pred='PACIFIC COD'
		--or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		--or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		--or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, 
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID, NPREY.ECOPATH_Prey, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN,PP.PRED_NODC, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"

	
	#______________________________________________________ predLen_lkup
	qry_PredPrey_lengths<-"SELECT 
		HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   
		--HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN,NPREY.ECOPATH_Prey, NPREY.Name as Species, 
		pp.PREY_SZ1,pp.PREY_SZ2,pp.PREY_SZ3,pp.EMPTY_1,pp.PREY_SEX,pp.PREYLENJOIN

		FROM foodlab.PREYLEN PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,kerim_strata TT
		, PREDLEN_LKUP CC
		--,racebase.haul HRB

		--WHERE (HH.GEAR_TEMP is not null) 
		WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND CC.PREDJOIN = PP.PREDJOIN 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )


		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, 
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID, NPREY.ECOPATH_Prey, NPREY.Name, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN,pp.PREY_SZ1,pp.PREY_SZ2,pp.PREY_SZ3,pp.EMPTY_1,pp.PREY_SEX,pp.PREYLENJOIN;"

	#______________________________________________________


	qry_LWA_all<-
	  "SELECT SS.CRUISE, SS.REGION, HH.START_LATITUDE, 
		HH.START_LONGITUDE, HH.STRATUM,TT.ECOPATH_PP,hh.start_time,
		hh.gear_temperature, hh.surface_temperature, 
		SS.SPECIES_CODE, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_Pred, SS.SEX, SS.AGE, SS.LENGTH, SS.WEIGHT

		FROM racebase.specimen SS, racebase.haul HH, foodlab.nodc NPRED,kerim_strata TT

		WHERE SS.hauljoin = HH.hauljoin AND SS.SPECIES_CODE = NPRED.race
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')

		AND SS.AGE IS NOT NULL
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		    
		ORDER BY NPRED.GOAPOLL_Pred, SS.SEX;"
	
	# AND (NPRED.ECOPATH_Pred='YELLOWFIN SOLE'
	# 	or NPRED.ECOPATH_Pred='WALLEYE POLLOCK'
	# 	or NPRED.ECOPATH_Pred='PACIFIC COD'
	# 	or NPRED.ECOPATH_Pred='FLATHEAD SOLE'
	# 	or NPRED.ECOPATH_Pred='ARROWTOOTH FLOUNDR'
	# 	or NPRED.ECOPATH_Pred='ROCK SOLE'
	# 	or NPRED.ECOPATH_Pred='Lg Sculpin'
	# 	or NPRED.ECOPATH_Pred='Salmon'
	# 	or NPRED.ECOPATH_Pred='PACIFIC HALIBUT'
	# 	or NPRED.ECOPATH_Pred='Misc. Flatfish'
	# 	or NPRED.ECOPATH_Pred='AK Plaice'
	# 	or NPRED.ECOPATH_Pred='Prickle squish round'
	# 	or NPRED.ECOPATH_Pred='Greenlings'
	# 	or NPRED.ECOPATH_Pred='Eelpout'
	# 	or NPRED.ECOPATH_Pred='GREENLAND TURBOT'
	# 	or NPRED.ECOPATH_Pred='Herring'
	# 	or NPRED.ECOPATH_Pred='BIG SKATE'
	# 	or NPRED.ECOPATH_Pred='Rex sole'
	# 	or NPRED.ECOPATH_Pred='ATKA MACKEREL'
	# 	or NPRED.ECOPATH_Pred='Macrouridae'
	# 	or NPRED.ECOPATH_Pred='Sculpin'
	# 	or NPRED.ECOPATH_Pred='AK SKATE'
	# 	or NPRED.ECOPATH_Pred='Eulachon'
	# 	or NPRED.ECOPATH_Pred='Unid Rajidae'
	# 	or NPRED.ECOPATH_Pred='SABLEFISH'
	# 	or NPRED.ECOPATH_Pred='POP'
	# 	or NPRED.ECOPATH_Pred='Aleutian Skate'
	# 	or NPRED.ECOPATH_Pred='Managed Forage'
	# 	or NPRED.ECOPATH_Pred='Northern Rock'
	# 	or NPRED.ECOPATH_Pred='Unid Bathyraja'
	# 	or NPRED.ECOPATH_Pred='Bering Skate'
	# 	or NPRED.ECOPATH_Pred='Bathylagidae'
	# 	or NPRED.ECOPATH_Pred='Capelin'
	# 	or NPRED.ECOPATH_Pred='Rougheye Rock'
	# 	or NPRED.ECOPATH_Pred='Dover Sole'
	# 	or NPRED.ECOPATH_Pred='Shortraker Rock'
	# 	or NPRED.ECOPATH_Pred='Dusky Rock'
	# 	or NPRED.ECOPATH_Pred='Giant Grenadier'
	# 	or NPRED.ECOPATH_Pred='Shortsp Thorny'
	# 	or NPRED.ECOPATH_Pred='Sharpchin Rock'
	# 	or NPRED.ECOPATH_Pred='Sleeper Shark'
	# 	or NPRED.ECOPATH_Pred='Sebastes'
	# 	or NPRED.ECOPATH_Pred='Black Skate'
	# 	or NPRED.ECOPATH_Pred='Mud Skate'
	# 	or NPRED.ECOPATH_Pred='Myctophidae'
	# 	or NPRED.ECOPATH_Pred='WhtBlotch Skate'
	# 	or NPRED.ECOPATH_Pred='Pacific Grenadier'
	# 	or NPRED.ECOPATH_Pred='Lingcod'
	# 	or NPRED.ECOPATH_Pred='Dogfish'
	# 	or NPRED.ECOPATH_Pred='Hake'
	# 	or NPRED.ECOPATH_Pred='Squid'
	# 	or NPRED.ECOPATH_Pred='Commander Skate'
	# 	or NPRED.ECOPATH_Pred='Oth pel. smelt'
	# 	or NPRED.ECOPATH_Pred='Sandlance'
	# 	or NPRED.ECOPATH_Pred='Prickle squish deep'
	# 	or NPRED.ECOPATH_Pred='Gen. Flatfish'
	# 	or NPRED.ECOPATH_Pred='Deepsea Skate'
	# 	or NPRED.ECOPATH_Pred='Canary Rock')
	# AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
	# 	or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
	# 	or NPRED.GOAPOLL_pred='PACIFIC COD'
	# 	or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
	# 	or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
	# 	or NPRED.GOAPOLL_pred='FLATHEAD SOLE'
	# 	or NPRED.GOAPOLL_pred='ROCK SOLE'
	# 	or NPRED.GOAPOLL_pred='GREENLAND TURBOT'
	# 	or NPRED.GOAPOLL_pred='BIG SKATE'
	# 	or NPRED.GOAPOLL_pred='ATKA MACKEREL'
	# 	or NPRED.GOAPOLL_pred='AK SKATE'
	# 	or NPRED.GOAPOLL_pred='SABLEFISH'
	# 	or NPRED.GOAPOLL_pred='Aleutian Skate'
	# 	or NPRED.GOAPOLL_pred='Bering Skate'
	# 	or NPRED.GOAPOLL_pred='Black Skate'
	# 	or NPRED.GOAPOLL_pred='Mud Skate'
	# 	or NPRED.GOAPOLL_pred='WhtBlotch Skate'
	# 	or NPRED.GOAPOLL_pred='Commander Skate'
	# 	or NPRED.GOAPOLL_pred='Deepsea Skate')
	#---------------------------------------------------------------
	
	qry_LW_all<-
	  "SELECT SS.CRUISE, SS.REGION, HH.START_LATITUDE, 
		HH.START_LONGITUDE, HH.STRATUM,TT.ECOPATH_PP,hh.start_time,
		hh.gear_temperature, hh.surface_temperature, 
		SS.SPECIES_CODE, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_Pred, SS.SEX, SS.AGE, SS.LENGTH, SS.WEIGHT

		FROM racebase.specimen SS, racebase.haul HH, foodlab.nodc NPRED,kerim_strata TT

		WHERE SS.hauljoin = HH.hauljoin AND SS.SPECIES_CODE = NPRED.race
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')

		AND (NPRED.ECOPATH_Pred <>  'NA' )
		    
		ORDER BY NPRED.GOAPOLL_Pred, SS.SEX;"
	
	# AND (NPRED.ECOPATH_Pred='YELLOWFIN SOLE'
	# 	or NPRED.ECOPATH_Pred='WALLEYE POLLOCK'
	# 	or NPRED.ECOPATH_Pred='PACIFIC COD'
	# 	or NPRED.ECOPATH_Pred='FLATHEAD SOLE'
	# 	or NPRED.ECOPATH_Pred='ARROWTOOTH FLOUNDR'
	# 	or NPRED.ECOPATH_Pred='ROCK SOLE'
	# 	or NPRED.ECOPATH_Pred='Lg Sculpin'
	# 	or NPRED.ECOPATH_Pred='Salmon'
	# 	or NPRED.ECOPATH_Pred='PACIFIC HALIBUT'
	# 	or NPRED.ECOPATH_Pred='Misc. Flatfish'
	# 	or NPRED.ECOPATH_Pred='AK Plaice'
	# 	or NPRED.ECOPATH_Pred='Prickle squish round'
	# 	or NPRED.ECOPATH_Pred='Greenlings'
	# 	or NPRED.ECOPATH_Pred='Eelpout'
	# 	or NPRED.ECOPATH_Pred='GREENLAND TURBOT'
	# 	or NPRED.ECOPATH_Pred='Herring'
	# 	or NPRED.ECOPATH_Pred='BIG SKATE'
	# 	or NPRED.ECOPATH_Pred='Rex sole'
	# 	or NPRED.ECOPATH_Pred='ATKA MACKEREL'
	# 	or NPRED.ECOPATH_Pred='Macrouridae'
	# 	or NPRED.ECOPATH_Pred='Sculpin'
	# 	or NPRED.ECOPATH_Pred='AK SKATE'
	# 	or NPRED.ECOPATH_Pred='Eulachon'
	# 	or NPRED.ECOPATH_Pred='Unid Rajidae'
	# 	or NPRED.ECOPATH_Pred='SABLEFISH'
	# 	or NPRED.ECOPATH_Pred='POP'
	# 	or NPRED.ECOPATH_Pred='Aleutian Skate'
	# 	or NPRED.ECOPATH_Pred='Managed Forage'
	# 	or NPRED.ECOPATH_Pred='Northern Rock'
	# 	or NPRED.ECOPATH_Pred='Unid Bathyraja'
	# 	or NPRED.ECOPATH_Pred='Bering Skate'
	# 	or NPRED.ECOPATH_Pred='Bathylagidae'
	# 	or NPRED.ECOPATH_Pred='Capelin'
	# 	or NPRED.ECOPATH_Pred='Rougheye Rock'
	# 	or NPRED.ECOPATH_Pred='Dover Sole'
	# 	or NPRED.ECOPATH_Pred='Shortraker Rock'
	# 	or NPRED.ECOPATH_Pred='Dusky Rock'
	# 	or NPRED.ECOPATH_Pred='Giant Grenadier'
	# 	or NPRED.ECOPATH_Pred='Shortsp Thorny'
	# 	or NPRED.ECOPATH_Pred='Sharpchin Rock'
	# 	or NPRED.ECOPATH_Pred='Sleeper Shark'
	# 	or NPRED.ECOPATH_Pred='Sebastes'
	# 	or NPRED.ECOPATH_Pred='Black Skate'
	# 	or NPRED.ECOPATH_Pred='Mud Skate'
	# 	or NPRED.ECOPATH_Pred='Myctophidae'
	# 	or NPRED.ECOPATH_Pred='WhtBlotch Skate'
	# 	or NPRED.ECOPATH_Pred='Pacific Grenadier'
	# 	or NPRED.ECOPATH_Pred='Lingcod'
	# 	or NPRED.ECOPATH_Pred='Dogfish'
	# 	or NPRED.ECOPATH_Pred='Hake'
	# 	or NPRED.ECOPATH_Pred='Squid'
	# 	or NPRED.ECOPATH_Pred='Commander Skate'
	# 	or NPRED.ECOPATH_Pred='Oth pel. smelt'
	# 	or NPRED.ECOPATH_Pred='Sandlance'
	# 	or NPRED.ECOPATH_Pred='Prickle squish deep'
	# 	or NPRED.ECOPATH_Pred='Gen. Flatfish'
	# 	or NPRED.ECOPATH_Pred='Deepsea Skate'
	# 	or NPRED.ECOPATH_Pred='Canary Rock')
	# AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
	# 	or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
	# 	or NPRED.GOAPOLL_pred='PACIFIC COD'
	# 	or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
	# 	or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
	# 	or NPRED.GOAPOLL_pred='FLATHEAD SOLE'
	# 	or NPRED.GOAPOLL_pred='ROCK SOLE'
	# 	or NPRED.GOAPOLL_pred='GREENLAND TURBOT'
	# 	or NPRED.GOAPOLL_pred='BIG SKATE'
	# 	or NPRED.GOAPOLL_pred='ATKA MACKEREL'
	# 	or NPRED.GOAPOLL_pred='AK SKATE'
	# 	or NPRED.GOAPOLL_pred='SABLEFISH'
	# 	or NPRED.GOAPOLL_pred='Aleutian Skate'
	# 	or NPRED.GOAPOLL_pred='Bering Skate'
	# 	or NPRED.GOAPOLL_pred='Black Skate'
	# 	or NPRED.GOAPOLL_pred='Mud Skate'
	# 	or NPRED.GOAPOLL_pred='WhtBlotch Skate'
	# 	or NPRED.GOAPOLL_pred='Commander Skate'
	# 	or NPRED.GOAPOLL_pred='Deepsea Skate')
	#---------------------------------------------------------------
	
	
	
	qry_King_crab<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   
		--HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, NPREY.Name as Species, 
		sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

		FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
		kerim_strata TT, CRAB_PRED_LKUP CC
		--, racebase.haul HRB

		--WHERE (HH.GEAR_TEMP is not null) 
		WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND CC.PREDJOIN = PP.PREDJOIN 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(NPREY.GOAPOLL_PREY = 'KING CRAB')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		--AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		--or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		--or NPRED.GOAPOLL_pred='PACIFIC COD'
		--or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		--or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		--or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, 
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID, NPREY.ECOPATH_Prey, NPREY.Name, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"

	#---------------------------------------------------------------
	
	qry_King_crab_lengths<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   
		--HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN,NPREY.ECOPATH_Prey, NPREY.Name as Species, 
		pp.PREY_SZ1,pp.PREY_SZ2,pp.PREY_SZ3,pp.EMPTY_1,pp.PREY_SEX,pp.PREYLENJOIN

		--, 
		--sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

		FROM foodlab.PREYLEN PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
		kerim_strata TT, CRAB_PREDLEN_LKUP CC 
		--,racebase.haul HRB

		WHERE (HH.GEAR_TEMP is not null) 
		AND (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		AND PP.PRED_NODC = NPRED.nodc 
		AND PP.PREY_NODC = NPREY.nodc 
		AND CC.PREDJOIN = PP.PREDJOIN 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(NPREY.GOAPOLL_PREY = 'KING CRAB')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		--AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		--or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		--or NPRED.GOAPOLL_pred='PACIFIC COD'
		--or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		--or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		--or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG,
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID, NPREY.ECOPATH_Prey, NPREY.Name, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN,pp.PREY_SZ1,pp.PREY_SZ2,pp.PREY_SZ3,pp.EMPTY_1,pp.PREY_SEX,pp.PREYLENJOIN;"

	#---------------------------------------------------------------
	
	qry_srvy_catch<-"SELECT NPRED.ECOPATH_Pred as SPECIES,NPRED.GOAPOLL_pred, 
		--HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID,
		HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN,
		HH.STATIONID, HH.RLAT, HH.RLONG,  
		--HRB.START_LATITUDE as RLAT_RACEBASE,
		--HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP
		--PP.PREDJOIN, PP.PRED_LEN, NPREY.ECOPATH_Prey

		FROM kerim_strata TT, racebase.haul HH, racebase.catch CC, foodlab.nodc NPRED

		--WHERE (HH.GEAR_TEMP is not null) 
		Where (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
		--AND PP.PRED_NODC = NPRED.nodc 
		--AND PP.PREY_NODC = NPREY.nodc 
		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
		--AND(NPREY.GOAPOLL_PREY = 'KING CRAB')
		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
		AND (NPRED.ECOPATH_Pred <>  'NA' )
		AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
		or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
		or NPRED.GOAPOLL_pred='PACIFIC COD'
		or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
		or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
		or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, 
		HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
		HH.VESSEL, HH.CRUISE, HH.HAUL,
		HH.GEAR_TEMP, 
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, 
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID, NPREY.ECOPATH_Prey, 
		HH.CRUISE_TYPE,TT.ECOPATH_PP;
		--,PP.PREDJOIN, PP.PRED_LEN;"

	#---------------------------------------------------------------
	qry_KH_AK_SST_BT_sub<-"SELECT HH.HAULJOIN, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP,
		HH.SURFACE_TEMP,  HH.STATIONID, HH.RLAT, HH.RLONG,   
		--HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
		HH.CRUISE_TYPE,TT.ECOPATH_PP

		FROM foodlab.haul HH,kerim_strata TT
		--racebase.haul HRB

		WHERE (HH.GEAR_TEMP is not null) 
		--AND (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
		--AND (HH.VESSEL = HRB.VESSEL AND HH.CRUISE = HRB.CRUISE AND HH.HAUL = HRB.HAUL) 
		AND  (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 

		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')

		GROUP BY  HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, HH.VESSEL, HH.CRUISE, HH.HAUL, 
		HH.GEAR_TEMP,
		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, 
		--HRB.START_LATITUDE, HRB.START_LONGITUDE, 
		HH.STATIONID,
		HH.CRUISE_TYPE,TT.ECOPATH_PP;"

	#---------------------------------------------------------------
	## Survey catch and biomass full table
	qry_SRVY_BIOM<-"SELECT  
		CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
		SP.SPECIES_NAME, SP.COMMON_NAME,NPRED.ECOPATH_PRED, NPRED.GOAPOLL_PRED, NPRED.GOAPOLL_PREY,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , AA.START_LATITUDE , AA.END_LATITUDE ,AA.START_LONGITUDE , AA.END_LONGITUDE , AA.STATIONID, 
		STAT.LATITUDE as SLAT, STAT.LONGITUDE as SLON,STAT.STRATUM as STRATUM, 
		AA.SUBSAMPLE,
		AA.DURATION , AA.DISTANCE_FISHED, AA.NET_WIDTH , AA.NET_MEASURED , AA.NET_HEIGHT,
		(AA.NET_WIDTH*AA.DISTANCE_FISHED)/10 as AREA_FISHED_HA,
		CC.WEIGHT/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_KGHA,
		CC.NUMBER_FISH/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_NOHA


		FROM RACEBASE.CATCH CC, 
			foodlab.haul HH, foodlab.nodc NPRED,
			kerim_strata TT, RACEBASE.HAUL AA, 
			RACEBASE.SPECIES SP, RACEBASE.STATIONS STAT,
			HOLSMANK.PREDLIST_LKUP plkup

		WHERE NPRED.RACE = CC.SPECIES_CODE
		AND  AA.HAULJOIN = CC.HAULJOIN 
		AND  (AA.STRATUM = AA.STRATUM AND AA.REGION =AA.REGION) 
		AND (CC.VESSEL = AA.VESSEL AND AA.CRUISE = HH.CRUISE AND AA.HAUL = HH.HAUL)
		AND NPRED.RACE=SP.SPECIES_CODE
		AND STAT.STATIONID=AA.STATIONID
		AND AA.HAUL_TYPE=3
		AND AA.PERFORMANCE>=0
		AND plkup.RACE=SP.SPECIES_CODE

		GROUP BY CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
				SP.SPECIES_NAME, SP.COMMON_NAME,NPRED.ECOPATH_PRED, NPRED.GOAPOLL_PRED, NPRED.GOAPOLL_PREY,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , AA.START_LATITUDE , AA.END_LATITUDE ,AA.START_LONGITUDE , AA.END_LONGITUDE,AA.STATIONID, 
		STAT.LATITUDE, STAT.LONGITUDE,STAT.STRATUM, 
		AA.SUBSAMPLE,
		AA.DURATION , AA.DISTANCE_FISHED, AA.NET_WIDTH , AA.NET_MEASURED , AA.NET_HEIGHT ;"


	#---------------------------------------------------------------
	qry_BIOM_WT_LKUP<-"SELECT CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION as REGIONC,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
		SP.SPECIES_NAME, SP.COMMON_NAME,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , 
		CC.WEIGHT/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_KGHA,
		CC.NUMBER_FISH/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_NOHA

CC.HAULJOIN,CC.CATCHJOIN,CC.REGION,CC.VESSEL,CC.CRUISE ,CC.HAUL ,
CC.SPECIES_CODE,CC.SPECIES_NAME,CC.COMMON_NAME,
sum(BB.CPUE_KGHA)

		FROM 
			RACEBASE.CATCH CC, 
			HOLSMANK.SRVY_BIOM bb, 
			foodlab.haul HH, foodlab.nodc NPRED,
			kerim_strata TT, RACEBASE.HAUL AA, 
			RACEBASE.SPECIES SP, RACEBASE.STATIONS STAT

		WHERE NPRED.RACE = CC.SPECIES_CODE
		AND  AA.HAULJOIN = CC.HAULJOIN 
		AND  (AA.STRATUM = AA.STRATUM AND AA.REGION =AA.REGION) 
		AND (CC.VESSEL = AA.VESSEL AND AA.CRUISE = HH.CRUISE AND AA.HAUL = HH.HAUL)
		AND NPRED.RACE=SP.SPECIES_CODE
		AND STAT.STATIONID=AA.STATIONID

		GROUP BY CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
				SP.SPECIES_NAME, SP.COMMON_NAME,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , AA.START_LATITUDE , AA.END_LATITUDE ,AA.START_LONGITUDE , AA.END_LONGITUDE,AA.STATIONID, 
		STAT.LATITUDE, STAT.LONGITUDE,STAT.STRATUM, 
		AA.SUBSAMPLE,
		AA.DURATION , AA.DISTANCE_FISHED, AA.NET_WIDTH , AA.NET_MEASURED , AA.NET_HEIGHT ;"


# qry_CATCHold<-"SELECT  CC.CRUISEJOIN, CC.HAULJOIN as HAULJOINC, 
# CC.CATCHJOIN,CC.REGION as REGIONC,
# CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
# CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN

# FROM RACEBASE.CATCH CC, foodlab.haul HH, foodlab.nodc NPRED,kerim_strata TT

# GROUP BY CC.CRUISEJOIN, CC.HAULJOIN, 
# CC.CATCHJOIN,CC.REGION,
# CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
# CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN;"
# 	qry_CATCHold2<-"SELECT NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred,
# 		NPRED.ECOPATH_Prey,NPRED.NAME,HH.REGION, HH.STRATUM, 
# 		HH.YEAR, HH.MONTH, HH.DAY,HH.VESSEL, HH.CRUISE, HH.HAUL,HH.GEAR_TEMP, 
# 		HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG, 
# 		HH.CRUISE_TYPE,TT.ECOPATH_PP, CC.CRUISEJOIN, CC.HAULJOIN as HAULJOINC, 
# 		CC.CATCHJOIN,CC.REGION as REGIONC,CC.WEIGHT, CC.NUMBER_FISH, 
# 		CC.SUBSAMPLE_CODE, CC.VOUCHER, CC.AUDITJOIN

# 		FROM RACEBASE.CATCH CC, foodlab.haul HH, foodlab.nodc NPRED,kerim_strata TT

# 		WHERE NPRED.RACE = CC.SPECIES_CODE
# 		AND  HH.HAULJOIN = CC.HAULJOIN 
# 		AND  (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 		AND (CC.VESSEL = HH.VESSEL AND CC.CRUISE = HH.CRUISE AND CC.HAUL = HH.HAUL)

# 		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred,NPRED.ECOPATH_Prey,NPRED.NAME, 
# 		HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, HH.VESSEL, HH.CRUISE, HH.HAUL,
# 		HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, 
# 		HH.RLONG,HH.CRUISE_TYPE,TT.ECOPATH_PP,CC.CRUISEJOIN, CC.HAULJOIN, 
# 		CC.CATCHJOIN,CC.REGION,CC.WEIGHT, CC.NUMBER_FISH, 
# 		CC.SUBSAMPLE_CODE, CC.VOUCHER, CC.AUDITJOIN;"
# 	#---------------------------------------------------------------
# 	#---------------------------------------------------------------
# 	#---------------------------------------------------------------
# 	qry4Anne<-"
# 			SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, 
# 			HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 			HH.VESSEL, HH.CRUISE, HH.HAUL, 
# 			HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,  
# 			HH.CRUISE_TYPE,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
# 			sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

# 			FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY

# 			WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
# 			AND PP.PRED_NODC = NPRED.nodc 
# 			AND PP.PREY_NODC = NPREY.nodc 
# 			AND(hh.region = 'GOA')
# 			AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 			AND (NPRED.ECOPATH_Pred <>  'NA' )
# 			AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
# 			or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
# 			or NPRED.GOAPOLL_pred='PACIFIC COD'
# 			or NPRED.GOAPOLL_pred='PACIFIC HALIBUT')

# 			GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred,
# 			HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, HH.VESSEL, HH.CRUISE, HH.HAUL,
# 			HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, HH.STATIONID, 
# 			NPREY.ECOPATH_Prey, 
# 			HH.CRUISE_TYPE,
# 			PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"





# 	qry4Anne2<-"
# 			SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, 
# 			HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 			HH.VESSEL, HH.CRUISE, HH.HAUL, TT.ECOPATH_PP,
# 			HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,  
# 			HH.CRUISE_TYPE,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
# 			sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

# 			FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,kerim_strata TT

# 			WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
# 			AND PP.PRED_NODC = NPRED.nodc 
# 			AND PP.PREY_NODC = NPREY.nodc 
# 			AND(hh.region = 'GOA')
# 			AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 			AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 			AND (NPRED.ECOPATH_Pred <>  'NA' )
# 			AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
# 			or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
# 			or NPRED.GOAPOLL_pred='PACIFIC COD'
# 			or NPRED.GOAPOLL_pred='PACIFIC HALIBUT')

# 			GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred,
# 			HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, HH.VESSEL, HH.CRUISE, HH.HAUL,TT.ECOPATH_PP,
# 			HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, HH.STATIONID, 
# 			NPREY.ECOPATH_Prey, 
# 			HH.CRUISE_TYPE,
# 			PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"



# 	qry4Anne3<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 			HH.VESSEL, HH.CRUISE, HH.HAUL, 
# 			HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
# 			HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
# 			sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

# 			FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
# 			kerim_strata TT, racebase.haul HRB

# 			WHERE (HH.GEAR_TEMP is not null) 
# 			AND (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
# 			AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
# 			AND PP.PRED_NODC = NPRED.nodc 
# 			AND PP.PREY_NODC = NPREY.nodc 
# 			AND(hh.region = 'GOA')
# 			AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 			AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 			AND (NPRED.ECOPATH_Pred <>  'NA' )
# 			AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
# 			or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
# 			or NPRED.GOAPOLL_pred='PACIFIC COD'
# 			or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
# 			or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
# 			or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

# 			GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 			HH.VESSEL, HH.CRUISE, HH.HAUL,
# 			HH.GEAR_TEMP, 
# 			HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, HRB.START_LATITUDE, HRB.START_LONGITUDE, HH.STATIONID, NPREY.ECOPATH_Prey, 
# 			HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"

# 	qry4Anne4<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 			HH.VESSEL, HH.CRUISE, HH.HAUL,
# 			HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,  
# 			HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
# 			sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

# 			FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
# 			kerim_strata TT

# 			WHERE (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
# 			AND PP.PRED_NODC = NPRED.nodc 
# 			AND PP.PREY_NODC = NPREY.nodc 
# 			AND(hh.region = 'GOA')
# 			AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 			AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 			AND (NPRED.ECOPATH_Pred <>  'NA' )
# 			AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
# 			or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
# 			or NPRED.GOAPOLL_pred='PACIFIC COD'
# 			or NPRED.GOAPOLL_pred='YELLOWFIN SOLE'
# 			or NPRED.GOAPOLL_pred='PACIFIC HALIBUT'
# 			or NPRED.GOAPOLL_pred='FLATHEAD SOLE')

# 			GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 			HH.VESSEL, HH.CRUISE, HH.HAUL,
# 			HH.GEAR_TEMP, 
# 			HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG,  HH.STATIONID, NPREY.ECOPATH_Prey, 
# 			HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"



# 	qry4Anne5<-"SELECT HH.HAULJOIN||'_'|| PP.PREDJOIN as PPID, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 	 	HH.VESSEL, HH.CRUISE, HH.HAUL, 
# 	 	HH.GEAR_TEMP, HH.SURFACE_TEMP, HH.HAULJOIN, HH.STATIONID, HH.RLAT, HH.RLONG,   HRB.START_LATITUDE as RLAT_RACEBASE, HRB.START_LONGITUDE as RLONG_RACEBASE,  
# 	 	HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full,NPREY.ECOPATH_Prey, 
# 	 	sum(PP.PREY_TWT) as TWT, sum(PP.PREY_CNT)as CNT, avg(pp.pred_dig)as DIG

# 	 	FROM foodlab.predprey PP, foodlab.haul HH, foodlab.nodc NPRED, foodlab.nodc NPREY,
# 	 	kerim_strata TT, racebase.haul HRB

# 	 	WHERE (HH.GEAR_TEMP is not null) 
# 	 	AND (PP.VESSEL = HH.VESSEL AND PP.CRUISE = HH.CRUISE AND PP.HAUL = HH.HAUL) 
# 	 	AND (PP.VESSEL = HRB.VESSEL AND PP.CRUISE = HRB.CRUISE AND PP.HAUL = HRB.HAUL) 
# 	 	AND PP.PRED_NODC = NPRED.nodc 
# 	 	AND PP.PREY_NODC = NPREY.nodc 
# 	 	AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 	 	--AND(hh.region = 'BS')
# 	 	AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 	 	AND (NPRED.ECOPATH_Pred <>  'NA' )
# 	 	AND (NPRED.GOAPOLL_pred='ARROWTOOTH FLOUNDR'
# 	 		or NPRED.GOAPOLL_pred='WALLEYE POLLOCK'
# 	 		or NPRED.GOAPOLL_pred='PACIFIC COD'
# 	 		or NPRED.GOAPOLL_pred='PACIFIC HALIBUT')

# 		GROUP BY NPRED.ECOPATH_Pred, NPRED.GOAPOLL_pred, HH.REGION, HH.STRATUM, HH.YEAR, HH.MONTH, HH.DAY, 
# 		HH.VESSEL, HH.CRUISE, HH.HAUL,
# 		HH.GEAR_TEMP, 
# 		HH.SURFACE_TEMP, HH.HAULJOIN, HH.RLAT,HH.RLONG, HRB.START_LATITUDE, HRB.START_LONGITUDE, HH.STATIONID, NPREY.ECOPATH_Prey, 
# 		HH.CRUISE_TYPE,TT.ECOPATH_PP,PP.PREDJOIN, PP.PRED_LEN, pp.pred_wt, pp.pred_full;"


