
### Rcode to query SQL RACEBASE
## K holsman 2021

#################################
## !!! Must be run in 32 bit R
#################################


# Core SQL functions:
#------------------------------------
location_sql        <-  function(surveyIN = 98 ){
  return(paste(
  "SELECT TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR, \n",
  "RACEBASE.HAUL.HAULJOIN as HAULJOIN, \n",
  "RACEBASE.HAUL.VESSEL AS VESSEL, \n",
  "RACEBASE.HAUL.CRUISE AS CRUISE, \n",
  "RACEBASE.HAUL.HAUL AS HAUL, \n",
  "EXTRACT(Month FROM RACEBASE.HAUL.START_TIME) as MONTH,\n",
  "EXTRACT(Day FROM RACEBASE.HAUL.START_TIME) as DAY,\n",
  "RACEBASE.HAUL.STRATUM,\n",
  "RACEBASE.HAUL.STATIONID,\n",
  "RACEBASE.HAUL.GEAR_TEMPERATURE AS TEMP, \n",
  "RACEBASE.HAUL.SURFACE_TEMPERATURE AS SST, \n",
  "RACEBASE.HAUL.BOTTOM_DEPTH AS DEPTH, \n",
  "RACEBASE.HAUL.END_LATITUDE AS LAT, \n",
  "RACEBASE.HAUL.END_LONGITUDE AS LON \n",
  "FROM RACE_DATA.V_CRUISES \n",
  "INNER JOIN RACEBASE.HAUL \n",
  "ON RACE_DATA.V_CRUISES.CRUISEJOIN = RACEBASE.HAUL.CRUISEJOIN \n",
  "WHERE RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID IN (", paste0(surveyIN,collapse=","),") \n",
  "AND RACEBASE.HAUL.HAUL_TYPE = 3 \n",
  "AND RACEBASE.HAUL.PERFORMANCE >= 0 \n", 
  "AND RACEBASE.HAUL.STATIONID IS NOT NULL",sep="")  )
}

# /km^2, If you prefer hectares, change the "1000" in the CPUE script to "10"
location_catch_sql        <-  function(surveyIN = 98, speciesIN = 10120 ){
  return(paste(
     "SELECT TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR, \n",
     "RACEBASE.HAUL.HAULJOIN as HAULJOIN, \n",
     "RACEBASE.HAUL.VESSEL AS VESSEL, \n",
     "RACEBASE.HAUL.CRUISE AS CRUISE, \n",
     "RACEBASE.HAUL.HAUL AS HAUL, \n", 
     "RACEBASE.HAUL.STRATUM,\n",
     "RACEBASE.HAUL.END_LATITUDE AS LAT, \n",
     "RACEBASE.HAUL.END_LONGITUDE AS LON, \n",
     "RACEBASE.CATCH.NUMBER_FISH/(RACEBASE.HAUL.DISTANCE_FISHED*(RACEBASE.HAUL.NET_WIDTH/1000)) AS CPUE_NUMKM2, \n",
     "RACEBASE.CATCH.WEIGHT/(RACEBASE.HAUL.DISTANCE_FISHED*(RACEBASE.HAUL.NET_WIDTH/1000)) AS CPUE_KGKM2, \n",
     "RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID, \n",
     "RACEBASE.CATCH.SPECIES_CODE \n",
     "FROM RACE_DATA.V_CRUISES \n",
     "INNER JOIN RACEBASE.HAUL \n",
     "ON RACE_DATA.V_CRUISES.CRUISEJOIN = RACEBASE.HAUL.CRUISEJOIN \n",
     "INNER JOIN RACEBASE.CATCH \n",
     "ON RACEBASE.HAUL.CRUISEJOIN = RACEBASE.CATCH.CRUISEJOIN \n",
     "AND RACEBASE.HAUL.HAULJOIN   = RACEBASE.CATCH.HAULJOIN \n",
     "AND RACEBASE.HAUL.VESSEL     = RACEBASE.CATCH.VESSEL \n",
     "AND RACEBASE.HAUL.CRUISE     = RACEBASE.CATCH.CRUISE \n",
     "AND RACEBASE.HAUL.HAUL       = RACEBASE.CATCH.HAUL \n",
     "WHERE RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID IN (", paste0(surveyIN,collapse=","),") \n",
     "AND RACEBASE.HAUL.HAUL_TYPE = 3 \n",
     "AND RACEBASE.HAUL.PERFORMANCE >= 0 \n", 
     "AND RACEBASE.HAUL.STATIONID IS NOT NULL \n",  
     "AND RACEBASE.CATCH.SPECIES_CODE IN (", paste0(speciesIN,collapse=","),")", sep=""))
}

LWA_table_sql  <- function(surveyIN = 98, speciesIN = 10120 ){
  return(paste (
    "SELECT TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR, \n",
    "RACEBASE.HAUL.HAULJOIN as HAULJOIN, \n",
    "RACEBASE.HAUL.VESSEL AS VESSEL, \n",
    "RACEBASE.HAUL.CRUISE AS CRUISE, \n",
    "RACEBASE.HAUL.HAUL AS HAUL, \n",
    "RACEBASE.HAUL.STRATUM,\n",
    "RACEBASE.HAUL.STATIONID,\n",
    "RACEBASE.SPECIMEN.LENGTH, \n",
    "RACEBASE.SPECIMEN.SPECIMENID, \n",
    "RACEBASE.SPECIMEN.SEX, \n",
    "RACEBASE.SPECIMEN.WEIGHT, \n",
    "RACEBASE.SPECIMEN.AGE, \n",
    "RACEBASE.HAUL.GEAR_TEMPERATURE AS TEMP, \n",
    "RACEBASE.HAUL.SURFACE_TEMPERATURE AS SST, \n",
    "RACEBASE.HAUL.BOTTOM_DEPTH AS DEPTH, \n",
    "RACEBASE.HAUL.END_LATITUDE AS LAT, \n",
    "RACEBASE.HAUL.END_LONGITUDE AS LON, \n",
    "RACEBASE.SPECIMEN.SPECIES_CODE, \n",
    "RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID \n",  
    "FROM RACE_DATA.V_CRUISES \n",
    "INNER JOIN RACEBASE.HAUL \n",
    "ON RACE_DATA.V_CRUISES.CRUISEJOIN = RACEBASE.HAUL.CRUISEJOIN \n",
    "INNER JOIN RACEBASE.SPECIMEN \n",
    "ON RACEBASE.HAUL.CRUISEJOIN                    = RACEBASE.SPECIMEN.CRUISEJOIN \n",
    "AND RACEBASE.HAUL.HAULJOIN                     = RACEBASE.SPECIMEN.HAULJOIN \n",
    "AND RACEBASE.HAUL.VESSEL                     = RACEBASE.SPECIMEN.VESSEL \n",
    "AND RACEBASE.HAUL.CRUISE                     = RACEBASE.SPECIMEN.CRUISE \n",
    "AND RACEBASE.HAUL.HAUL                     = RACEBASE.SPECIMEN.HAUL \n",
    
    "WHERE RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID IN (", paste0(surveyIN,collapse=","),") \n",
    "AND RACEBASE.HAUL.HAUL_TYPE                    = 3 \n",
    "AND RACEBASE.HAUL.PERFORMANCE                 >= 0 \n",
    "AND RACEBASE.HAUL.STATIONID                   IS NOT NULL \n",  
    "AND RACEBASE.SPECIMEN.SPECIES_CODE IN (", paste0(speciesIN,collapse=","),")", sep=""))
}

length_sql <-  function(surveyIN = 98, speciesIN = 10120 ){
  return(paste(
    "SELECT TO_CHAR(RACEBASE.HAUL.START_TIME, 'yyyy') AS YEAR, \n",
     "RACEBASE.HAUL.HAULJOIN as HAULJOIN, \n",
     "RACEBASE.HAUL.VESSEL AS VESSEL, \n",
     "RACEBASE.HAUL.CRUISE AS CRUISE, \n",
     "RACEBASE.HAUL.HAUL AS HAUL, \n",
     "RACEBASE.HAUL.STRATUM,\n",
     "RACEBASE.LENGTH.LENGTH, \n",
     "RACEBASE.LENGTH.FREQUENCY, \n",
     "RACEBASE.LENGTH.SEX, \n",
     "RACEBASE.HAUL.GEAR_TEMPERATURE AS TEMP, \n",
     "RACEBASE.HAUL.BOTTOM_DEPTH AS DEPTH, \n",
     "RACEBASE.HAUL.END_LATITUDE AS LAT, \n",
     "RACEBASE.HAUL.END_LONGITUDE AS LON, \n",
     "RACEBASE.LENGTH.SPECIES_CODE, \n",
     "RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID \n",  
    
     "FROM RACE_DATA.V_CRUISES \n",
     "INNER JOIN RACEBASE.HAUL \n",
     "ON RACE_DATA.V_CRUISES.CRUISEJOIN = RACEBASE.HAUL.CRUISEJOIN \n",
     "INNER JOIN RACEBASE.LENGTH \n",
     "ON RACEBASE.HAUL.CRUISEJOIN  = RACEBASE.LENGTH.CRUISEJOIN \n",
     "AND RACEBASE.HAUL.HAULJOIN   = RACEBASE.LENGTH.HAULJOIN \n",
     "AND RACEBASE.HAUL.VESSEL     = RACEBASE.LENGTH.VESSEL \n",
     "AND RACEBASE.HAUL.CRUISE     = RACEBASE.LENGTH.CRUISE \n",
     "AND RACEBASE.HAUL.HAUL       = RACEBASE.LENGTH.HAUL \n",
     
     "WHERE RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID IN (", paste0(surveyIN,collapse=","),") \n",
     "AND RACEBASE.HAUL.HAUL_TYPE                    = 3 \n",
     "AND RACEBASE.HAUL.PERFORMANCE                 >= 0 \n",
     "AND RACEBASE.HAUL.STATIONID                   IS NOT NULL \n",  
     "AND RACEBASE.LENGTH.SPECIES_CODE IN (", paste0(speciesIN,collapse=","),")", sep=""))
}


# Older defunct functions:
#---------------------------------------------------------------
## Survey catch and biomass full table

qry_SRVY_BIOM<-"SELECT  
		CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
		SP.SPECIES_NAME, SP.COMMON_NAME,NPRED.ECOPATH_PRED, NPRED.GOAPOLL_PRED, NPRED.GOAPOLL_PREY,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , AA.START_LATITUDE , AA.END_LATITUDE ,AA.START_LONGITUDE , AA.END_LONGITUDE , AA.STATIONID, 
		STAT.LATITUDE as SLAT, STAT.LONGITUDE as SLON,STAT.STRATUM as STRATUM, 
		AA.SUBSAMPLE,
		AA.DURATION , AA.DISTANCE_FISHED, AA.NET_WIDTH , AA.NET_MEASURED , AA.NET_HEIGHT,
		(AA.NET_WIDTH*AA.DISTANCE_FISHED)/10 as AREA_FISHED_HA,
		CC.WEIGHT/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_KGHA,
		CC.NUMBER_FISH/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_NOHA


		FROM RACEBASE.CATCH CC, 
			foodlab.haul HH, foodlab.nodc NPRED,
			kerim_strata TT, RACEBASE.HAUL AA, 
			RACEBASE.SPECIES SP, RACEBASE.STATIONS STAT,
			HOLSMANK.PREDLIST_LKUP plkup

		WHERE NPRED.RACE = CC.SPECIES_CODE
		AND  AA.HAULJOIN = CC.HAULJOIN 
		AND  (AA.STRATUM = AA.STRATUM AND AA.REGION =AA.REGION) 
		AND (CC.VESSEL = AA.VESSEL AND AA.CRUISE = HH.CRUISE AND AA.HAUL = HH.HAUL)
		AND NPRED.RACE=SP.SPECIES_CODE
		AND STAT.STATIONID=AA.STATIONID
		AND AA.HAUL_TYPE=3
		AND AA.PERFORMANCE>=0
		AND plkup.RACE=SP.SPECIES_CODE

		GROUP BY CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
				SP.SPECIES_NAME, SP.COMMON_NAME,NPRED.ECOPATH_PRED, NPRED.GOAPOLL_PRED, NPRED.GOAPOLL_PREY,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , AA.START_LATITUDE , AA.END_LATITUDE ,AA.START_LONGITUDE , AA.END_LONGITUDE,AA.STATIONID, 
		STAT.LATITUDE, STAT.LONGITUDE,STAT.STRATUM, 
		AA.SUBSAMPLE,
		AA.DURATION , AA.DISTANCE_FISHED, AA.NET_WIDTH , AA.NET_MEASURED , AA.NET_HEIGHT ;"


#---------------------------------------------------------------
qry_BIOM_WT_LKUP<-"SELECT CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION as REGIONC,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
		SP.SPECIES_NAME, SP.COMMON_NAME,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , 
		CC.WEIGHT/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_KGHA,
		CC.NUMBER_FISH/((AA.NET_WIDTH*AA.DISTANCE_FISHED)/10) as CPUE_NOHA

CC.HAULJOIN,CC.CATCHJOIN,CC.REGION,CC.VESSEL,CC.CRUISE ,CC.HAUL ,
CC.SPECIES_CODE,CC.SPECIES_NAME,CC.COMMON_NAME,
sum(BB.CPUE_KGHA)

		FROM 
			RACEBASE.CATCH CC, 
			HOLSMANK.SRVY_BIOM bb, 
			foodlab.haul HH, foodlab.nodc NPRED,
			kerim_strata TT, RACEBASE.HAUL AA, 
			RACEBASE.SPECIES SP, RACEBASE.STATIONS STAT

		WHERE NPRED.RACE = CC.SPECIES_CODE
		AND  AA.HAULJOIN = CC.HAULJOIN 
		AND  (AA.STRATUM = AA.STRATUM AND AA.REGION =AA.REGION) 
		AND (CC.VESSEL = AA.VESSEL AND AA.CRUISE = HH.CRUISE AND AA.HAUL = HH.HAUL)
		AND NPRED.RACE=SP.SPECIES_CODE
		AND STAT.STATIONID=AA.STATIONID

		GROUP BY CC.CRUISEJOIN, CC.HAULJOIN, 
		CC.CATCHJOIN,CC.REGION,
		CC.VESSEL, CC.CRUISE, CC.HAUL, CC.SPECIES_CODE,
				SP.SPECIES_NAME, SP.COMMON_NAME,
		CC.WEIGHT, CC.NUMBER_FISH,CC.SUBSAMPLE_CODE,CC.VOUCHER,CC.AUDITJOIN,
		AA.GEAR_DEPTH, AA.BOTTOM_DEPTH, AA. BOTTOM_TYPE, AA. SURFACE_TEMPERATURE, AA. GEAR_TEMPERATURE, 
		AA.STRATUM , AA.START_LATITUDE , AA.END_LATITUDE ,AA.START_LONGITUDE , AA.END_LONGITUDE,AA.STATIONID, 
		STAT.LATITUDE, STAT.LONGITUDE,STAT.STRATUM, 
		AA.SUBSAMPLE,
		AA.DURATION , AA.DISTANCE_FISHED, AA.NET_WIDTH , AA.NET_MEASURED , AA.NET_HEIGHT ;"

# #---------------------------------
# qry_LWA_all<- paste0("SELECT SS.CRUISE,SS.REGION, HH.START_LATITUDE, 
# 		HH.START_LONGITUDE, 
# 		HH.STRATUM,
# 		TT.ECOPATH_PP,
# 		hh.start_time,
# 		hh.gear_temperature, 
# 		hh.surface_temperature, 
# 		SS.SPECIES_CODE, 
# 		NPRED.ECOPATH_Pred, 
# 		NPRED.GOAPOLL_Pred, 
# 		SS.SEX, 
# 		SS.AGE, 
# 		SS.LENGTH, 
# 		SS.WEIGHT
# 		--RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID
# 		
# 		FROM RACE_DATA.V_CRUISES,racebase.specimen SS, racebase.haul HH, foodlab.nodc NPRED,kerim_strata TT
# 		--INNER JOIN RACEBASE.HAUL 
# 		--ON RACE_DATA.V_CRUISES.CRUISEJOIN = RACEBASE.HAUL.CRUISEJOIN
# 		
# 		WHERE SS.hauljoin = HH.hauljoin AND SS.SPECIES_CODE = NPRED.race
# 		--AND RACE_DATA.V_CRUISES.CRUISEJOIN = HH.CRUISEJOIN
# 		--AND RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID IN (",paste0(srvys$num ,collapse=","),")
# 		AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 		AND SS.AGE IS NOT NULL
# 		AND (NPRED.ECOPATH_Pred <>  'NA' )
# 		
#     ORDER BY NPRED.GOAPOLL_Pred, SS.SEX;")
# # cat(qry_LWA_all)
# # sqlQuery(con,qry_LWA_all)
# #---------------------------------------------------------------
# 
# qry_LW_all<- paste0(
#   "SELECT SS.CRUISE, SS.REGION, HH.START_LATITUDE, 
# 		HH.START_LONGITUDE, HH.STRATUM,TT.ECOPATH_PP,hh.start_time,
# 		hh.gear_temperature, hh.surface_temperature, 
# 		SS.SPECIES_CODE, NPRED.ECOPATH_Pred, NPRED.GOAPOLL_Pred, SS.SEX, SS.AGE, SS.LENGTH, SS.WEIGHT	
# 		--RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID
# 		FROM RACE_DATA.V_CRUISES,racebase.specimen SS, racebase.haul HH, foodlab.nodc NPRED,kerim_strata TT
# 
# 		WHERE SS.hauljoin = HH.hauljoin AND SS.SPECIES_CODE = NPRED.race
# 		--AND RACE_DATA.V_CRUISES.CRUISEJOIN = HH.CRUISEJOIN
# 		--AND RACE_DATA.V_CRUISES.SURVEY_DEFINITION_ID IN (",paste0(srvys$num ,collapse=","),")
# 	  AND (HH.STRATUM = TT.STRATUM AND HH.REGION =TT.REGION) 
# 		--AND(hh.CRUISE_TYPE = 'Race_Groundfish')
# 
# 		AND (NPRED.ECOPATH_Pred <>  'NA' )
# 		    
# 		ORDER BY NPRED.GOAPOLL_Pred, SS.SEX;")
# 
# #---------------------------------------------------------------

